/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AgentExecutionsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GuestUsersTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "TaskIntegrationsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "TaskManagerWeb": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
    "TaskQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "TaskWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "TasksTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UsersTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WorkspaceIntegrationsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WorkspacesTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}